### ISSUE TITLE
README.md has a broken link for docs

### ISSUE THREAD

**Issue by dingwilson** [Clarifai/clarifai-ios#15]
The README.md contains a broken link.

> Read the full Objective-C docs at: https://sdk.clarifai.com/iOS/docs-{{version-number}}/masterTOC.html

The last "working" documentation link seems to be [2.0.0](https://sdk.clarifai.com/iOS/docs-2.0.0/masterTOC.html), as 2.0.1, 2.0.2, and 2.0.3 don't seem to work.

**Comment by jpgsloan** [comment]
fixing this shortly, thanks
