### ISSUE TITLE
in Xcode 8 my app gets stuck at Recognizing and doesn't progress.

### ISSUE THREAD

**Issue by sureshb** [Clarifai/clarifai-ios#8]
Anyone else seeing the same issue in Xcode 8 ? I have updated the client id and secret but never get past Recognizing..

**Comment by jpgsloan** [comment]
sorry for the delay, looking into this. Are you using the swift example or obj-c? If you are using the obj-c example, make sure to change it in the main storyboard to point towards the RecognitionViewController class. By default the storyboard runs with the swift example. So if you only changed the id and secret in RecognitionViewController.m that may be the issue.

**Comment by sureshb** [comment]
I’m using Swift.

Thanks,
Suresh




On October 6, 2016 at 12:16:58 PM, John Patrick Sloan (
notifications@github.com) wrote:

sorry for the delay, looking into this. Are you using the swift example or
obj-c? If you are using the obj-c example, make sure to change it in the
main storyboard to point towards the RecognitionViewController class. By
default the storyboard runs with the swift example. So if you only changed
the id and secret in RecognitionViewController.m that may be the issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Clarifai/clarifai-ios/issues/8#issuecomment-252061457>,
or mute the thread

**Comment by sureshb** [comment]
I downloaded the project, updated the keys and tried. Thats all I did. So
should be easily reproducible.

Thanks,
Suresh



On October 6, 2016 at 12:16:58 PM, John Patrick Sloan (
notifications@github.com) wrote:

sorry for the delay, looking into this. Are you using the swift example or
obj-c? If you are using the obj-c example, make sure to change it in the
main storyboard to point towards the RecognitionViewController class. By
default the storyboard runs with the swift example. So if you only changed
the id and secret in RecognitionViewController.m that may be the issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Clarifai/clarifai-ios/issues/8#issuecomment-252061457>,
or mute the thread

**Comment by jpgsloan** [comment]
Hmm I can't seem to reproduce the problem. Where did you add your id and secret? In Credentials.swift?

**Comment by sureshb** [comment]
Correct. 

Thanks,
SB




On Thu, Oct 6, 2016 at 6:38 PM -0700, "John Patrick Sloan" <notifications@github.com> wrote:












Hmm I can't seem to reproduce the problem. Where did you add your id and secret? In Credentials.swift?

**Comment by jpgsloan** [comment]
Ok cool, that's definitely the problem then. We mistakenly left that file in, you should be adding the credentials directly in SwiftRecognitionViewController.swift in the recognizeImage method.

I'll make sure this is fixed in an upcoming update. As well as an update to the readme instructions.

**Comment by sureshb** [comment]
Let me try that and get back to you.
Thanks.



On October 6, 2016 at 8:43:09 PM, John Patrick Sloan (
notifications@github.com) wrote:

Ok cool, that's definitely the problem then. We mistakenly left that file
in, you should be adding the credentials directly in
SwiftRecognitionViewController.swift in the recognizeImage method.

I'll make sure this is fixed in an upcoming update. As well as an update to
the readme instructions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Clarifai/clarifai-ios/issues/8#issuecomment-252146373>,
or mute the thread

**Comment by sureshb** [comment]
Excellent, yes got it working now. Appreciate your help.

Thanks,
Suresh



On October 6, 2016 at 8:43:09 PM, John Patrick Sloan (
notifications@github.com) wrote:

Ok cool, that's definitely the problem then. We mistakenly left that file
in, you should be adding the credentials directly in
SwiftRecognitionViewController.swift in the recognizeImage method.

I'll make sure this is fixed in an upcoming update. As well as an update to
the readme instructions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Clarifai/clarifai-ios/issues/8#issuecomment-252146373>,
or mute the thread
